apiVersion: kubernetes.dask.org/v1
kind: DaskCluster
metadata:
  name: example
  labels:
    foo: bar
spec:
  worker:
    replicas: 0
    spec:
      restartPolicy: Never
      containers:
      - name: worker
        image: "hermelinkluntjes/thesis:test"
        imagePullPolicy: "Always"
        args: [dask-worker, --no-dashboard , '--name', $(DASK_WORKER_NAME)]
        env:
          - name: EXTRA_PIP_PACKAGES
            value: git+https://github.com/dask/distributed jupyter-server-proxy
        resources:
          requests:
            cpu: "2"
            memory: 6G
  scheduler:
    spec:
      containers:
      - name: scheduler
        image: "hermelinkluntjes/thesis:test"
        imagePullPolicy: "Always"
        args: [dask-scheduler]
        env:
          - name: EXTRA_PIP_PACKAGES
            value: jupyterlab jupyter-server-proxy
        ports:
          - name: tcp-comm
            containerPort: 8786
            protocol: TCP
          - name: http-dashboard
            containerPort: 8787
            protocol: TCP
        readinessProbe:
          httpGet:
            port: http-dashboard
            path: /health
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            port: http-dashboard
            path: /health
          initialDelaySeconds: 5
          periodSeconds: 20
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
    service:
      type: ClusterIP
      selector:
        dask.org/cluster-name: example
        dask.org/component: scheduler
      ports:
      - name: tcp-comm
        protocol: TCP
        port: 8786
        targetPort: "tcp-comm"
      - name: http-dashboard
        protocol: TCP
        port: 8787
        targetPort: "http-dashboard"