distributed:
  scheduler:
    preload:
    - src                           # or a module name
    preload-argv:
    - []                                  # Pass optional keywords
    - []
  worker:
    preload: []
    preload-argv: []
  nanny:
    preload: []
    preload-argv: []
  client:
    preload: []
    preload-argv: []