environment: colab

model:
  data:
    test_cutoff_date: "2021-01-01"
    val_cutoff_date: "2022-01-01"
  input_col_name: "parsed_body"
  target_col_name: "r_mkt_adj"

data:
  iqfeed:
    minute:
      raw: "gs://extreme-lore-398917-bzg/iqfeed/raw"
      cleaned: "gs://extreme-lore-398917-bzg/iqfeed/cleaned"
    daily:
      raw: "D:/IQFeedData/daily"
  
  benzinga:
    raw: 
    cleaned: "/content/drive/MyDrive/NewsTrading/trading_bot/data//bzg/processed_news" 

  merged: "/content/drive/MyDrive/NewsTrading/trading_bot/data/news.parquet"

