environment: colab

data:
  iqfeed:
    minute:
      raw: "gs://extreme-lore-398917-bzg/iqfeed/raw"
      cleaned: "gs://extreme-lore-398917-bzg/iqfeed/cleaned"
    daily:
      raw: "D:/IQFeedData/daily"
  
  benzinga:
    raw: 
    cleaned: "data/bzg/processed_news.parquet" 
    input_ids: "data/bzg/input_ids.parquet" 
    masks: "data/bzg/masks.parquet" 

  merged: "/content/drive/MyDrive/NewsTrading/trading_bot/data/news.parquet"

