environment: colab

data:
  iqfeed:
    minute:
      raw: "gs://extreme-lore-398917-bzg/iqfeed/raw"
      cleaned: "gs://extreme-lore-398917-bzg/iqfeed/cleaned"
    daily:
      raw: "D:/IQFeedData/daily"
  
  benzinga:
    raw: 
    cleaned: "/content/drive/MyDrive/NewsTrading/trading_bot/data/bzg/processed_news.parquet" 
    encoding_matrix: "D:/Data/Merged/encoding_matrix.npy"

  merged: "/content/drive/MyDrive/NewsTrading/trading_bot/data/news.parquet"

