environment: local

data:
  iqfeed:
    minute:
      raw: "D:/IQFeedData/minute/raw"
      cleaned: "D:/IQFeedData/minute/cleaned"
    daily:
      raw: ""
      cleaned: "D:/IQFeedData/daily/cleaned"
  
  benzinga:
    raw: data/bzg/raw
    raw_html_parsed: data/bzg/html_parsed.parquet
    cleaned: "data/bzg/processed_news.parquet" 
    input_ids: "D:/Data/bzg/input_ids.parquet"
    masks: "D:/Data/bzg/masks.parquet"
    ticker_name_mapper: "data_shared/ticker_name_mapper.parquet"
    corporation_endings: "data_shared/corporation_endings.txt"

  merged: "data/merged/news.parquet"
  learning_dataset: "data/learning_dataset.parquet"
