model:
  data:
    training: "D:/Data/NN_Training"
    testing: "D:/Data/NN_Testing"
    cutoff_date: "2021-01-01"
  input_col_name: "body"
  target_col_name: "r_mkt_adj"

data:
  iqfeed:
    minute:
      raw: "D:/IQFeedData"
      cleaned: "D:/IQFeedData/cleaned_1min"
    daily:
      raw: "D:/IQFeedData/daily"
  
  benzinga:
    raw: 

