environment: local

data:
  iqfeed:
    minute:
      raw: "data/iqfeed/minute/raw"
      cleaned: "data/iqfeed/minute/cleaned"
    daily:
      raw: ""
      cleaned: "data/iqfeed/daily/cleaned"
  
  benzinga:
    raw: "data/bzg/raw_bzg"
    raw_html_parsed: "data/bzg/html_parsed"

  fnspid: 
    raw: "data/fnspid/raw.csv"
    raw_html_parsed: "data/fnspid/html_parsed.parquet"

  news:
    raw_html_parsed: "data/news/raw_html_parsed.parquet" 
    cleaned: "data/news/processed_news.parquet" 
    stripped: "data/news/stripped.parquet"
    input_ids: "data/news/input_ids.parquet"
    masks: "data/news/masks.parquet"
    title_only:
      input_ids: "data/news/title_only/input_ids.parquet"
      masks: "data/news/title_only/masks.parquet"

  shared:
    corporation_endings: "data_shared/corporation_endings.txt"
    ticker_name_mapper: "data_shared/ticker_name_mapper.parquet"
    ticker_name_mapper_reduced: "data_shared/ticker_name_mapper_reduced.parquet"
    ticker_name_mapper_consolidated: "data_shared/ticker_name_mapper_consolidated.parquet"

  merged: "data/merged_dataset.parquet"
  learning_dataset: "data/learning_dataset.parquet"
  predictions:
    regression_dir: "data/predictions/regression"
