#program: src/model/training.py
name: sweepdemo
method: bayes

#controller:
#          type: local

metric:
  goal: minimize
  name: val/loss

parameters:
  hidden_layer_size: 
    values: [128, 786]
  learning_rate:
    distribution: loguniform
    min: 0.0001
    max: 0.1
  batch_size:
    values: [16, 32, 64]
  dropout_rate:
    value: 0
  epochs:
    value: 2
  fast_dev_run: 
    value: false
  stop_after_lr_finder: 
    value: false
  ckpt: 
    value: none
  deactivate_bert_learning: 
    value: true  
