program: src/model/training.py
name: sweepdemo
method: bayes

metric:
  goal: minimize
  name: val/loss

parameters:
  hidden_layer_size: 
    values: [128, 786]
  learning_rate:
    distribution: lognormal
    min: 1e-5
    max: 0.1
  batch_size:
    values: [16, 32, 64]
  dropout_rate:
    values: [0, 0.2]
  epochs:
    value: 2

  fast_dev_run: 
    value: False,
  stop_after_lr_finder: 
    value: False,
  ckpt": 
    value: None,
  num_samples: 
    value: 4
  deactivate_bert_learning: 
    value: True  